- README.md
- package.json
- "dxs" is still set as an alias
> feat(cli): change default command to "dxscanner"

- README.md
Fix the name of DX Heroes twitter
> fix(README): add right DX_Heroes twitter

- README.md
> fix: name of the project

- README.md
Extend the about section and add supported languages table.
> Feat(readme): extend the README

- CONTRIBUTING.md
Improve the contribution guide.
> Docs: Contribution guide

- src/practices/JavaScript/DeprecatedTSLintPractice.ts
- src/practices/JavaScript/ESLintUsedPractice.ts
- src/practices/JavaScript/JsBackendTestingFrameworkUsedPractice.ts
- src/practices/JavaScript/JsFEBuildToolUsedPractice.ts
- src/practices/JavaScript/JsFrontendTestingFrameworkUsedPractice.ts
- src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
- src/practices/JavaScript/JsGitignoreIsPresentPractice.ts
- src/practices/JavaScript/JsLoggerUsedPractice.ts
- src/practices/JavaScript/JsPackageJsonConfigurationSetCorrectlyPractice.ts
- src/practices/JavaScript/JsPackageManagementUsedPractice.ts
- src/practices/JavaScript/PrettierUsedPractice.ts
- src/practices/JavaScript/TypeScriptUsedPractice.ts
- src/practices/LanguageIndependent/CIUsedPractice.ts
- src/practices/LanguageIndependent/DependenciesVersionPractice.ts
- src/practices/LanguageIndependent/DockerizationUsedPractice.ts
- src/practices/LanguageIndependent/EditorConfigIsPresentPractice.ts
- src/practices/LanguageIndependent/LicenseIsPresentPractice.ts
- src/practices/LanguageIndependent/ReadmeIsPresentPractice.ts
- src/practices/PackageManagement/LockfileIsPresentPractice.ts
> fix: Rename practices

- src/practices/LanguageIndependent/DependenciesVersionPractice.ts
fix: add suggestion text and url
> fix: add suggestion text and url

- src/scanner/Scanner.ts
Pass the scanStrategy parameter into detectProjectComponents() to have a remote URL for printing the report.
> fix(scanner): display remote url in report

- package.json
- src/scanner/ScannerUtils.ts
- typings/toposort.d.ts
- yarn.lock
Remove custom toposort typings as the requested changes in the package were merged. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37104/files
> Feat(toposort): Remove custom toposort typings.

- README.md
fix: name of contributor
feat: add aliases to readme,
> fix(README): fix command for installing

- src/practices/LanguageIndependent/DependenciesVersionPractice.ts
Change suggestion text as we've started to use Renovate Bot isstead of GreenKeeper.
> chore: Change suggestion text

- .travis.yml
add a condition to deploy if Linux build passes.
> feat(CI): add scripts to run on travis

- src/contexts/language/languageContextBinding.ts
- src/detectors/Java/JavaComponentDetector.ts
- src/inspectors/package/JavaPackageInspector.ts
Working detection => manually tested on:
```bash
yarn start https://github.com/ryzzaki/spring-booted-endpoints
```
> Java Component Detector + Java Package Inspector

- bin/postinstall
- bin/postinstall.cmd
- package.json
- yarn.lock
> Added postinstall in package.json

- src/contexts/scanner/scannerContextBinding.ts
- src/detectors/Python/PythonLanguageDetector.spec.ts
- src/detectors/Python/PythonLanguageDetector.ts
- src/model.ts
> Language Detector for Python

- src/detectors/Golang/GolangLanguageDetector.spec.ts
- src/detectors/Golang/GolangLanguageDetector.ts
> feat: add golang language detector

- src/detectors/Cpp/CppLanguageDetector.spec.ts
- src/detectors/Cpp/CppLanguageDetector.ts
> feat: add cpp language detector

- src/detectors/PHP/PHPLanguageDetector.spec.ts
- src/detectors/PHP/PHPLanguageDetector.ts
- src/model.ts
> feat: add php language detector

- src/detectors/Ruby/RubyLanguageDetector.spec.ts
- src/detectors/Ruby/RubyLanguageDetector.ts
> feat: add ruby language detector

- README.md
- src/practices/JavaScript/DependenciesVersionPractice.ts
- src/practices/JavaScript/DeprecatedTSLintPractice.ts
- src/practices/JavaScript/ESLintUsedPractice.ts
- src/practices/JavaScript/JsBackendTestingFrameworkUsedPractice.ts
- src/practices/JavaScript/JsFEBuildToolUsedPractice.ts
- src/practices/JavaScript/JsFrontendTestingFrameworkUsedPractice.ts
- src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
- src/practices/JavaScript/JsLoggerUsedPractice.ts
- src/practices/JavaScript/JsPackageJsonConfigurationSetCorrectlyPractice.ts
- src/practices/JavaScript/JsPackageManagementUsedPractice.ts
- src/practices/JavaScript/PrettierUsedPractice.ts
- src/practices/JavaScript/TypeScriptUsedPractice.ts
- src/practices/LanguageIndependent/CIUsedPractice.ts
- src/practices/LanguageIndependent/DockerizationUsedPractice.ts
- src/practices/LanguageIndependent/EditorConfigIsPresentPractice.ts
- src/practices/LanguageIndependent/GitignoreIsPresentPractice.ts
- src/practices/LanguageIndependent/LicenseIsPresentPractice.ts
- src/practices/LanguageIndependent/ReadmeIsPresentPractice.ts
- src/practices/PackageManagement/LockfileIsPresentPractice.ts
- src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts
Please check what version of Master did I use... I'm completely lost!
> Practices - Updates

- src/detectors/ScanningStrategyDetector.ts
- src/services/bitbucket/BitbucketService.ts
- src/services/git/GitServiceUtils.ts
- src/services/git/model.ts
Fixed URL parsing for reporters.
Related to #153
> fix(bitbucket): attempt to fix bitbucket URL parsing

- src/detectors/Java/JavaComponentDetector.ts
- src/practices/Java/JavaPackageManagementUsed.spec.ts
- src/practices/Java/JavaPackageManagementUsed.ts
- src/practices/JavaScript/JsPackageManagementUsedPractice.spec.ts
- src/practices/JavaScript/JsPackageManagementUsedPractice.ts
- src/practices/index.ts
This PR will add a new practice for Java in order to check whether the project uses a package management framework like Maven or Gradle. This PR thereby solves Issue #211
> feat(java): package management used practice

- README.md
- src/contexts/fixer/FixerContext.ts
- src/index.ts
- src/practices/IPractice.ts
- src/practices/JavaScript/ESLintWithoutErrorsPractice.ts
- src/scanner/ArgumentsProvider.ts
- src/scanner/Scanner.spec.ts
- src/scanner/Scanner.ts
- src/test/factories/ArgumentsProviderFactory.ts
Proof of concept, implement CLI flag and simple fixer for one rule
TODO: 
TODO later: config fixer granularity from config
> Add automatic fix interface

- src/practices/Java/JavaTestingFrameworkUsedPractice.spec.ts
- src/practices/Java/JavaTestingFrameworkUsedPractice.ts
- src/practices/index.ts
This PR aims to solve issue #216
> feat: java practices that check testing frameworks

- .travis.yml
- src/commands/init.ts
- src/inspectors/FileInspector.spec.ts
- src/scanner/Scanner.ts
Fix all tests and init function for Windows architecture. We expect no failure in the Windows pipeline since now.
we want to support Windows
> fix(init): Win architecture & tests

- README.md
- package.json
- src/scanner/ConfigProvider.ts
- src/scanner/IConfigProvider.ts
- src/scanner/Scanner.spec.ts
- src/scanner/Scanner.ts
- src/test/jest.setupFileAfterEnv.ts
- yarn.lock
> Fixer flag in configuration

- src/practices/JavaScript/SecurityVulnerabilitiesPractice.spec.ts
- src/practices/JavaScript/SecurityVulnerabilitiesPractice.ts
If `npm audit` fails, the SecurityVulnerabilities practice crashed.
> Fix SecurityVulnerabilities npm audit error

- src/inversify.config.ts
- src/reporters/CLIReporter.ts
- src/reporters/FixReporter.ts
- src/reporters/IReporter.ts
- src/reporters/builders/CIReportBuilder.ts
- src/reporters/index.ts
- src/scanner/Scanner.ts
- src/test/factories/PracticeWithContextFactory.ts
Add new reporter for showing info about fixes being made during the fix run
Example of fixer output
User should have some info about what was fixed during the fix run and how it affected the score.
> Custom fixer report

- package.json
- src/practices/LanguageIndependent/LicenseIsPresentPractice.ts
- yarn.lock
Automatic fixer for `LanguageIndependent.LicenseIsPresent` Practice
The fixer runs and interactive prompt, which will let user picks a license and some other details.
TODO: What should happen when the fixer runs in non-interactive environment? There are multiple options:
- don't run it
- run it and generate some default license (which one?)
- run it only when preferred license is set in dxs config
This also needs to be resolved for the sake of adding some tests
> Automatic fixer for license practice

- .travis.yml
- src/reporters/CLIReporter.ts
- src/reporters/IReporter.ts
- src/services/gitlab/gitlabClient/resources/Issues.ts
- src/services/gitlab/gitlabClient/resources/Projects.ts
- src/services/gitlab/gitlabClient/resources/UsersOrGroups.ts
- src/services/gitlab/gitlabClient/resources/model.ts
- src/test/factories/responses/gitLab/listPrsResponseFactory.ts
> ci: set cache name by build ID

- yarn.lock
The release job is failing because of missing semantic-release/changelog module but that's not true so I am trying to update all libs.
> chore: upgrade libs

- .travis.yml
Fixes failing release job in master branch. This PR was just for debugging purpose.
> chore: debug failing CI

- Dockerfile
- src/reporters/CIReporter.ts
- src/services/gitlab/gitlabClient/GitLabClient.ts
- src/services/gitlab/gitlabClient/resources/MergeRequests.ts
The CI reporter doesn't support Gitlab CI.
To have a comments with DX report in PR.
> feat(gitlab): support CI reporter

- src/reporters/FixReporter.ts
Fixer reporter was missing info about practices that could not be fixed. Which may result in an empty report.
> Info about not-fixed practices in fixer reporter

- src/practices/JavaScript/SecurityVulnerabilitiesPractice.ts
- src/practices/PackageManagement/LockfileIsPresentPractice.spec.ts
- src/practices/PackageManagement/LockfileIsPresentPractice.ts
- src/practices/utils/PackageManagerUtils.ts
Add automatic fixer for `LanguageIndependent.LockfileIsPresent` practice
> Add fixer for lockfile practice

- src/contexts/projectComponent/projectComponentContextBinding.ts
This PR will solve issue #267 with small hotfix changes.
> fix: scanning local repos without git hotfix

- yarn.lock
> fix: update lockfile

- src/practices/JavaScript/DependenciesVersionMinorPatchLevel.spec.ts
- src/practices/JavaScript/DependenciesVersionMinorPatchLevel.ts
- types/npm-check-updates/index.d.ts
:exclamation:  This depends on #273 Do not merge before #273 is merged  :exclamation:
Add automatic fixer for patch and minor Javascript dependencies
> Fixer for JS patch and minor deps

- src/inspectors/CollaborationInspector.ts
- src/inspectors/ICollaborationInspector.ts
- src/inspectors/IIssueTrackingInspector.ts
- src/inspectors/IssueTrackingInspector.ts
- src/practices/LanguageIndependent/DoesPullRequests.spec.ts
The Travis Pipeline fails because of the Rate limit. I have added a Cache to inspectors.
> feat(inspectors): cache all functions in CollaborationInspector and IssueInspector

- src/detectors/ScanningStrategyDetector.ts
- src/index.ts
- src/lib/errors/errorHandler.ts
- src/lib/errors/index.ts
> Better error handling

- package.json
- src/practices/TypeScript/TsGitignoreCorrectlySetPractice.spec.ts
- src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts
- yarn.lock
Add fixer for TS gitignore practice. Fixer also tries to make a sensible guess of output folder/file based on tsconfig
> Add fixer for TS gitignore

- Dockerfile
- entrypoint.sh
This removes a node setup code from our Dockerfile. Also using the alpine version brings the image size down.
bash => sh and apt-get => apk changes are due to alpine version
We want to make the Docker distribution of dxs smaller
> Use node dockerfile image

- src/reporters/EnterpriseReporter.spec.ts
- src/reporters/EnterpriseReporter.ts
Add version and id to enterprise report
> feat: add version and id to enterprise report

- src/services/git/GitHubService.ts
- src/services/git/OctokitTypes.ts
- src/services/git/VCSServicesUtils.spec.ts
- src/services/git/VCSServicesUtils.ts
> Hotfix: failing build due to new version of packages

- src/reporters/EnterpriseReporter.spec.ts
- src/reporters/EnterpriseReporter.ts
> fix: data report

- entrypoint.sh
> Fix Dockerfile "starts with" check

- src/contexts/scanner/scannerContextBinding.ts
- src/reporters/EnterpriseReporter.ts
- src/scanner/Scanner.ts
Send data to DXSE if apiToken is provided or repo is public
> chore: send data if apiToken is provided or repo is public

- bin/run
- package.json
- src/index.ts
We need to import types in external service so we need to re-export them from index file.
> feat(types): export types from the index.ts

- src/index.ts
- src/reporters/EnterpriseReporter.ts
- src/reporters/IReporter.ts
I added security issues types/interfaces and exported in index.
> feat: add exported types

- src/detectors/JavaScript/JavaScriptComponentDetector.ts
- add NestJS to backend packages
> fix: add nestjs to backend packages for JS/TS

- src/index.ts
- src/reporters/EnterpriseReporter.ts
> feat: add updated dependencies dto

- src/reporters/DashboardReporter.spec.ts
- src/reporters/DashboardReporter.ts
> feat: send serviceType

- src/scanner/Scanner.ts
There was a bug - the repository paths of components were stored badly.
> fix: storing rootPath

- src/services/git/GitServiceUtils.spec.ts
- src/services/git/GitServiceUtils.ts
- do not add /tree/* if the path is for root of repository
> fix: component repository path

- README.md
- src/commands/run.ts
Add info about dependencies to README and git check before the scanner run
> Docs update: dependencies info

- src/contexts/scanner/scannerContextBinding.ts
- src/reporters/CLIReporter.ts
- src/scanner/Scanner.ts
Don't run fix command for remote repos
> Don't run fix command for remote repos

- src/scanner/Scanner.ts
Add warning when no languages detected, that the score will be zero.
> Add warning when no languages detected

- src/reporters/builders/CIReportBuilder.ts
Fixed CI reporter formatting for unknown, turned off and fixable practices
> Fix: CI reporter formatting for unknown, turned off and fixable practices

- README.md
I've added Hacktoberfest section to ReadMe to make participants informed.
Hacktoberfest will start in a few days and we want to show, that we are celebrating it and to provide necessary steps for contributors.
> update: added Hacktoberfest section to readme

- .mergify.yml
- .renovaterc
Do not use Renovate's automerge feature, as it might be a victim to race condition where Travis status checks are not initialized yet and Renovate merges automatically a build which then fails
Resolves #320
> Use mergify for renovate's PRs

- src/services/bitbucket/BitbucketService.ts
There is no client.authenticate function. This fixes the authentication
> Fix bitbucket authenticate

- src/practices/LanguageIndependent/CIUsedPractice.spec.ts
- src/practices/LanguageIndependent/CIUsedPractice.ts
Check for  Github Actions files in CI practices
Fixes #444
> feat: Support Github Actions in CI pratices

- src/services/gitlab/GitLabService.ts
- src/services/gitlab/gitlabClient/resources/UsersOrGroups.ts
- yarn.lock
> fix: get user info by email

- src/practices/Go/GoLinterUsedPractice.ts
- src/practices/Go/GoListerUsedPractice.spec.ts
- src/practices/index.ts
Add linter practice for Go project. Checking for the following packages:
- golang.org/x/lint
- github.com/golangci/golangci-lint
resolves #415
> feat: add linter practice for Go

- src/practices/LanguageIndependent/DoesPullRequests.ts
- src/services/git/model.ts
- src/services/gitlab/GitLabService.spec.ts
- src/services/gitlab/GitLabService.ts
- src/services/gitlab/gitlabClient/resources/UsersOrGroups.ts
- src/test/helpers/gitLabNock.ts
> fix: find user by email

- .github/FUNDING.yml
> feat: add funding file to get sponsor button on github

- src/collectors/BranchesCollector.ts
- src/collectors/ContributorsCollector.ts
- src/collectors/DataCollector.ts
- src/contexts/scanner/scannerContextBinding.ts
- src/inspectors/GitInspector.ts
- src/inspectors/IGitInspector.ts
- src/reporters/DashboardReporter.spec.ts
- src/reporters/DashboardReporter.ts
- src/services/bitbucket/BitbucketService.ts
- src/services/git/GitHubService.ts
- src/services/git/IVCSService.ts
- src/services/git/model.ts
- src/services/gitlab/GitLabService.ts
Add branches info to Dashboard report. Implemented only for BitBucket service for now.
> Send branch info to dashboard reporter

- README.md
- src/practices/LanguageIndependent/ReadmeCorrectlySetPractice.spec.ts
- src/practices/LanguageIndependent/ReadmeCorrectlySetPractice.ts
Practice for correctly set readme.md headings and add headings if not present
closes #396
> readme correctly set practice

- src/collectors/BranchesCollector.ts
- src/services/git/GitHubService.ts
List branch info for GitHub repositories
> Add GitHub branch list

- src/collectors/BranchesCollector.ts
- src/services/git/__MOCKS__/gitLabServiceMockFolder/listBranchesResponse.ts
- src/services/gitlab/GitLabService.spec.ts
- src/services/gitlab/GitLabService.ts
- src/services/gitlab/gitlabClient/gitlabUtils.ts
- src/services/gitlab/gitlabClient/resources/Branches.ts
- src/test/factories/responses/gitLab/branchResponseFactory.ts
- src/test/helpers/gitLabNock.ts
List branches for GitLab repositories
> Add branch list for GitLab

- README.md
- src/practices/Python/PythonLinterUsedPractice.spec.ts
- src/practices/Python/PythonLinterUsedPractice.ts
Linter used practice for python projects
Closes #420
> feat: linter used python practice 

- README.md
- src/commands/init.ts
- src/commands/practices.ts
- src/commands/run.ts
- src/index.ts
- src/model.ts
- src/reporters/DashboardReporter.ts
- src/scanner/ArgumentsProvider.ts
- src/test/factories/ArgumentsProviderFactory.ts
Add option to config API URL
Move default values of args to one place
> Add option to config API URL

- src/detectors/ScanningStrategyDetector.spec.ts
- src/detectors/ScanningStrategyDetector.ts
> Fallback to local path when repo scan fails

- src/practices/LanguageIndependent/CorrectCommitMessagesPractice.spec.ts
- src/practices/LanguageIndependent/CorrectCommitMessagesPractice.ts
> fix: change evaluation of CorrectCommitMessagesPractice

- src/inspectors/CollaborationInspector.spec.ts
- src/practices/LanguageIndependent/DoesPullRequests.spec.ts
- src/practices/LanguageIndependent/ThinPullRequestsPractice.ts
- src/services/git/Git.spec.ts
- src/services/git/GitHubService.spec.ts
- src/services/git/GitHubService.ts
- src/services/git/IGitHubService.ts
- src/services/git/VCSServicesUtils.ts
- src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullServiceResponse.mock.ts
- src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullsServiceResponse.mock.ts
- src/services/git/__MOCKS__/gitHubServiceMockFolder/gqlPullsResponse.mock.ts
- src/services/git/__MOCKS__/gitLabServiceMockFolder/getPullRequestResponse.ts
- src/services/git/gqlQueries/listPullRequests.ts
- src/services/git/model.ts
- src/services/gitlab/GitLabService.ts
> feat: filter prs by date

- src/services/FileSystemService.real.spec.ts
- src/services/__MOCKS__/mockFolder/mockFileSLbroken.ln
Broken symlink causes github action to crash
Remove broken symlink tests. Broken symlink file causes github action checkout to fail
> fix: remove broken symlink tests

- action.yml
- action/Dockerfile
- action/entrypoint.sh
Fixes GH action entrypoint script. Add missing git to action Dockerfile. Fix GH action specs
> Fix GH action Dockerfile spec

- .travis.yml
> Fix Dockerfile action build on Travis

- Dockerfile
> fix: Dockerfile chmod for entrypoint not versioned

- src/services/gitlab/GitLabService.ts
> fix: filter git lab contributors

- src/collectors/ContributorsCollector.ts
- src/contexts/language/languageContextBinding.ts
- src/contexts/projectComponent/projectComponentContextBinding.ts
- src/contexts/scanner/scannerContextBinding.ts
- src/detectors/ScanningStrategyDetector.spec.ts
- src/detectors/ScanningStrategyDetector.ts
- src/inspectors/IssueTrackingInspector.ts
- src/inspectors/package/RubyPackageInspector.ts
- src/practices/Go/GoGitignoreCorrectlySetPractice.spec.ts
- src/practices/Go/GoGitignoreCorrectlySetPractice.ts
- src/practices/LanguageIndependent/ChangelogIsPresentPractice.ts
- src/practices/LanguageIndependent/CorrectCommitMessagesPractice.spec.ts
- src/practices/LanguageIndependent/CorrectCommitMessagesPractice.ts
- src/practices/LanguageIndependent/DoesPullRequests.spec.ts
- src/practices/LanguageIndependent/DoesPullRequests.ts
- src/practices/LanguageIndependent/TimeToSolveIssuesPractice.spec.ts
- src/practices/LanguageIndependent/TimeToSolveIssuesPractice.ts
Do not fail when services are unknown.
> fix: do not fail when services are unknown

- src/contexts/scanner/scannerContextBinding.ts
When scanning private repo locally without token we didn't bind collectors.
> fix: update condition for binding collectors

- src/reporters/DashboardReporter.ts
Add debug in dashboard reporter
> fix: add debug in dashboard reporter

- src/commands/run.ts
safer option which let the pipeline continue
> Output zero exit code when practices fail on CI

- src/scanner/Scanner.ts
Clone repos are huge. The clone depth sets the commits to clone to 100.
- [] I have added tests to cover my changes.
> feat: simple git clone depth set to 100

- .github/workflows/node.js.yml
Add github actions build
Alternative to Travis builds. I didn't remove Travis config yet. There is a lot of repetition in YAML becuase Github actions does not support sharing parts of jobs yet.
> feat: add GH actions build

- src/reporters/CIReporter.ts
Google Cloud Build integration for CIReporter
> feat: Cloud Build integration for CI Reporter

- src/detectors/JavaScript/JavaScriptLanguageDetector.ts
- src/detectors/utils.spec.ts
- src/detectors/utils.ts
Add support for Bower components.
Resolves #538
> Add Bower support

- README.md
- src/commands/run.ts
- src/index.ts
- src/model.ts
Use recursive scan by default, when running in CI mode
> Recursive by default for CI mode

- src/reporters/builders/CIReportBuilder.ts
We were having issues with too long comments being rejected by Github. This removes large practice details info from CI reports.
> Remove CI reporter details
