package.json
src/index.ts
yarn.lock

Fixes #70
I have added [update-notifier](https://www.npmjs.com/package/update-notifier) with its default prompt.
update-notifier uses [is-installed-globally](https://github.com/sindresorhus/is-installed-globally) package to detect whether to show `npm i -g` in the message. The autodetection didn't work correctly for me, either because I have linked the package with `yarn link` or because it was run in other Node projects. Because the recommended use is to have this utility installed globally, I have forced the `isGlobal` option.
Change `version` field in `package.json` to lower version than published and run the CLI with `bin/run`. You should see the notification:
To retest, remove or modify `~/.config/configstore/update-notifier-dx-scanner.json` file.

feat(cli): add update-notifier

---

src/practices/LanguageIndependent/GitignoreIsPresentPractice.spec.ts
src/practices/LanguageIndependent/GitignoreIsPresentPractice.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.spec.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts
src/practices/index.ts

split gitignore correctly set to separated JS & TS
- because JS and TS has different content (e.g. JS doesn't have a build/dist folder)

feat(practices): split gitignore correctly set to separated JS & TS

---

bin/run

It's not possible to run the dx-scanner with `/bin/sh` because it isn't installed at all.
Related to #155

fix(cli): remove sh because windows doesn't have it installed

---

README.md
src/index.ts

Accept ENV variable DX_GIT_SERVICE_TOKEN instead of an authorization argument to be able to use secrets in Continuous Integrations.
Related to https://github.com/DXHeroes/dx-scanner/projects/2#card-29044383

feat(cli): do not require -a argument, accept env variable DX_GIT_SERVICE_TOKEN

---

src/index.ts
src/scanner/Scanner.ts

Fixed twice required bitbucket credentials when repository shared to me.
Need to finish:
Related to #153

fix(bitbucket): do not require bitbucket credentials twice

---

src/practices/JavaScript/JsGitignoreCorrectlySetPractice.spec.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.spec.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts

As mentioned in [npm](https://docs.npmjs.com/files/package-locks#using-locked-packages) and [yarn](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control) docs, adding lockfile to VCS might be perfectly valid option
Resolves #96

Do not require lockfiles in gitignore practice

---

src/practices/Java/JavaMockingFrameworkUsed.ts
src/practices/Java/JavaMockingFrameworkUsedPractice.spec.ts
src/practices/index.ts

This PR aims to solve issue #212

feat: java practice for detecting test mock frameworks

---

src/practices/Java/JavaLoggerUsedPractice.spec.ts
src/practices/Java/JavaLoggerUsedPractice.ts
src/practices/index.ts

This PR aims to solve issue #217

feat: java logger used practice

---

package.json
src/services/git/GitHubService.ts
yarn.lock

Update import of Octokit
Octokit has a deprecation notice
```[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead```

fix(services): deprecation notice removed

---

jest.config.js
src/detectors/ScanningStrategyDetector.spec.ts
src/inspectors/CollaborationInspector.spec.ts
src/inspectors/IssueTrackingInspector.spec.ts
src/lib/assertNever.spec.ts
src/practices/LanguageIndependent/CorrectCommitMessagesPractice.spec.ts
src/practices/LanguageIndependent/DoesPullRequests.spec.ts
src/practices/LanguageIndependent/ThinPullRequestsPractice.spec.ts
src/practices/LanguageIndependent/TimeToSolveIssuesPractice.spec.ts
src/practices/LanguageIndependent/TimeToSolvePullRequestsPractice.spec.ts
src/practices/index.ts
src/services/bitbucket/BitbucketService.spec.ts
src/services/git/Git.spec.ts
src/services/git/GitHubService.spec.ts
src/services/git/VCSServicesUtils.ts
src/test/helpers/bitbucketNock.ts
src/test/jest.setupFileAfterEnv.ts

- lint all and remove unnecessary imports and nocks

chore: lint all and remove unnecessary imports

---

src/detectors/Java/JavaLanguageDetector.spec.ts
src/inspectors/package/JavaPackageInspector.ts
src/inspectors/package/JavaPackageInspectorGradle.spec.ts
src/practices/Java/JavaGitignoreCorrectlySetPractice.spec.ts
src/practices/Java/JavaGitignoreCorrectlySetPractice.ts
src/practices/Java/JavaNamingConventionsPractice.spec.ts
src/practices/Java/JavaNamingConventionsPractice.ts
src/practices/Java/JavaPackageManagementUsedPractice.spec.ts
src/practices/Java/JavaPackageManagementUsedPractice.ts

This PR will fix the current Java practices and Inspector to accommodate for the Kotlin/Gradle variation involving `build.gradle.kts`.

fix: adjusting practices & inspector for gradle/kotlin variation

---

src/lib/errors/ErrorFactory.ts

Avoid circular dependency in `ErrorFactory.ts`
In current version, there is a circular dependency in `lib/errors/index.ts -> lib/errors/ErrorFactory.ts -> lib/errors/index.ts`. This was OK for some places, where `ErrorFactory` was required directly (e.g. `JSONUtils.ts`) but caused `ErrorFactory` to be just an empty object on places where it was required through `lib/errors/index.ts` (e.g. `ScannerUtils.ts`)
After this change, circular dependency is avoided and requiring `ErrorFactory` via `index.ts` won't result in empty object.

Use specific imports in ErrorFactory

---

src/detectors/ScanningStrategyDetector.ts
src/detectors/utils/ScanningStrategyDetectorUtils.ts
src/scanner/Scanner.ts
src/services/gitlab/GitLabService.ts
src/services/gitlab/gitlabClient/GitLabClient.ts

`dx-scanner run .` does not work on a project that is on GitLab. The GitLabClient didn't have the correct host in its attributes.
Now the scanning strategy detector works correctly. But there is another error https://github.com/DXHeroes/dx-scanner/issues/280

fix(gitlab): handle 404 error while scanning locally

---

src/commands/run.ts

This PR will solve issue #260 
Old behaviour (silent fail):
```
08:33 $ yarn start run --ci -r -a asdf
yarn run v1.22.0
$ ./bin/run run --ci -r -a asdf
WARNING: You're running DX Scanner in development mode.
Scanning URI: /Users/prokop/Sites/_dxheroes/scanner... done
Scan duration 0s.
✨  Done in 20.76s.
```
New behaviour:
```
/Users/cngng/Documents/Applifting/DX Scanner/dx-scanner/src/lib/errors/ErrorFactory.ts:20
return new ServiceError({
^
ServiceError: Invalid Authorization Credentials!
at Function.newAuthorizationError (/Users/cngng/Documents/Applifting/DX Scanner/dx-scanner/src/lib/errors/ErrorFactory.ts:20:12)
at Command.run (/Users/cngng/Documents/Applifting/DX Scanner/dx-scanner/src/commands/run.ts:40:26)
at processTicksAndRejections (internal/process/task_queues.js:85:5)
at async …
```

fix: running ci mode w/ invalid credentials

---

src/practices/Java/JavaDependenciesVersionMinorPatchLevel.spec.ts
src/practices/utils/DependenciesVersionEvaluationUtils.spec.ts
src/practices/utils/DependenciesVersionEvaluationUtils.ts

SemVer checker was evaluating major level updates as minor/patch level updated if they also updated a minor/patch level. Which (I believe) is not what we want. Minor level check should not return major level updates in any case.

Fix version util SemVer check

---

src/services/gitlab/gitlabClient/GitLabClient.ts

Do not reject unauthorized certificates in Gitlab Axios.
DX Scanner can not post a comment in a private Gitlab instance with a custom SSL certificate.

fix(gitlab): do not reject unauthorized certificates

---

package.json
src/inspectors/FileInspector.ts
src/inspectors/IFileInspector.ts
src/practices/JavaScript/PrettierUsedPractice.spec.ts
src/practices/JavaScript/PrettierUsedPractice.ts
src/practices/LanguageIndependent/EditorConfigIsPresentPractice.ts
src/practices/utils/PackageManagerUtils.ts
types/prettier-default-config/index.d.ts
yarn.lock

Add fixer for JavaScript.PrettierUsed practice.
It will:
- install prettier
- if not present, create prettier config with default prettier values
- if not present, add "format" npm script to package.json which runs the prettier
- default values in config are from prettier of DXS, not prettier which is installed
PackageManagerUtils code looks like it should be part of JavascriptPackageInspector - I want to move it there right after this MR

Fixer for Prettier present

---

src/detectors/ScanningStrategyDetector.spec.ts
src/detectors/ScanningStrategyDetector.ts
src/services/gitlab/GitLabService.spec.ts
src/services/gitlab/GitLabService.ts
src/services/gitlab/gitlabClient/resources/Projects.ts
src/services/gitlab/gitlabClient/resources/UsersOrGroups.ts
src/test/factories/responses/gitLab/listGroupsResponseFactors.ts
src/test/factories/responses/gitLab/listProjectsResponseFactory.ts
src/test/helpers/gitLabNock.ts

If the `/version` endpoints returned 403 because the user didn't provide an API key so the Scan fails with `InternalError: Unable to detect scanning strategy. It seems that the service is not implemented yet.` because it's not sure that the service is GitLab.
Now we call 2 more PUBLIC API endpoints specific for GitLab that can determine the service.

Better GitLab detection from more API endpoints

---

src/inspectors/FileInspector.ts
src/inspectors/IFileInspector.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.spec.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts

Add a fixer for JavaScript.GitignoreCorrectlySet practice. Does not add lockfiles, due to unknown package manager.

Fixer for JsGitignore practice

---

src/reporters/ReporterUtils.spec.ts
src/reporters/ReporterUtils.ts

If none of the practices is active, reporter score was `NaN %`. This fixes it.

Fix reporter NaN percentage

---

src/services/git/GitServiceUtils.spec.ts
src/services/git/GitServiceUtils.ts

Component path is often publicly visible in reporters (e.g. on GH) so we need to omit user credentials from URL, when necessary.

Omit creds from component path

---

package.json
src/practices/LanguageIndependent/LicenseIsPresentPractice.ts

Module is used while it's missing from package.json. It also adds console to `yeoman-environment` call.
Sorry for two changes in one PR but the build needs both to be green.
After yeoman-environment update from 2.8 to 2.9, it uses console.Console ctor, which is missing from console object when running jest tests. Therefore, we have to pass the console directly to yeoman-environment, so that it does not try to call console.Console at all

Add missing octokit dependency and fix LicenseIsPresent init

---

entrypoint.sh

This changes "ends with" check in Dockerfile's entrypoint to ash's syntax. ash is a shell being used by BusyBox's `sh`. Alpine Docker image is built on BusyBox
Running `sh` or `bash` in dx-scanner Docker image was crashing

Fix Dockerfile "ends with" check

---

src/commands/init.ts
src/commands/practices.ts
src/commands/run.ts
src/index.ts
src/model.ts
src/reporters/EnterpriseReporter.ts
src/scanner/ArgumentsProvider.ts
src/scanner/Scanner.ts
src/test/factories/ArgumentsProviderFactory.ts

Allow users to pass apiToken for DX Scanner Enterprise in CLI or env variables.

feat: allow users to pass apiToken in CLI or env variables

---

src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts

Move tsconfig package require to method.
Fixes problem with tsconfig when using dxscanner as a dependency.

fix: move tsconfig require

---

src/contexts/contexts.spec.ts
src/contexts/language/languageContextBinding.ts
src/detectors/ScanningStrategyDetector.spec.ts
src/detectors/ScanningStrategyDetector.ts
src/index.ts
src/inspectors/FileInspector.ts
src/reporters/EnterpriseReporter.ts
src/scanner/Scanner.ts
src/scanner/__MOCKS__/ScanningStrategy.mock.ts
src/services/model.ts

- to be able detect files for git from a root of a git repository
Some practices failed because the root path for browsing files was set to the input path instead of repository root path-
The root path of FileInspector should be a root path of a git repository for local scanning.

fix: use repository root path as a root path for FileInspector

---

src/practices/JavaScript/JsGitignoreCorrectlySetPractice.spec.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.spec.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts

This PR will fix the .gitignore practices which require *.lock files to be in the .gitignore. The lock files are preferred to not be ignored according to: https://github.com/yarnpkg/yarn/issues/1583

fix: relaxing conditions for .gitignore & fix tests

---

src/commands/init.ts
src/commands/practices.ts
src/commands/run.ts
src/index.ts
src/scanner/Scanner.ts

This PR will fix the multi-recursion problem. Running DXS without --recursive will still analyse all the components. This PR takes only the first component in the array and gives it back as a relevant component for the scanner analyse.

fix: recursion when the flag is false

---

package.json

Run jest tests sequentially instead of parallelly.
due to memory limit on many systems, they can't provide resources to run 92 test suites parallelly in which some of them require in 1600 MB to run hence running them sequentially will reduce many node processes from spanning at once which will prevent freeze of system to complete halt.
closes issue #439

run test sequentially in jest

---

src/contexts/language/LanguageContext.ts
src/inspectors/FileInspector.ts
src/scanner/Scanner.ts
src/services/FileSystemService.real.spec.ts
src/services/FileSystemService.ts
src/services/FileSystemService.virtual.spec.ts
src/services/git/Git.spec.ts
src/services/git/Git.ts

Update sequentially running loops for promise resolution to concurrently running promises using Promise.all while updating tests for two functions as promises are now run concurrently.
promise resolution sequentially takes a lot of time to resolve all when then can instead run concurrently.
closes #287

Promise all

---

src/services/bitbucket/BitbucketService.ts

DeepRequired was added a while ago to override shitty lib's typings (see https://github.com/DXHeroes/dx-scanner/commit/519346387174a90befceaa26edd5dd0a2be489de ) but it turned out, some of the fields can really be undefined in the API response.
DeepRequired then converts the response to the wrong type and the info about possible undefined of the field is lost. This fixes it.

Fix BitBucket commit list response type

---

Dockerfile

This modifies the Dockerfile to merge all the `RUN` commands at once rather than many commands.  
See: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers
In this case it does not reduce the overall size of the image at all (though it usually does in larger builds), however it still reduces the build time, and the number of image layers and intermediate images that are created during the build of the final image.
```
<none>              <none>              a97400b94f74        44 seconds ago       280MB
dxs-official        latest              8f7bc28ddbdc        44 seconds ago       280MB
<none>              <none>              c422e581e46d        45 seconds ago       280MB
<none>              <none>              665d4b0ad25e        45 …
```

fix: Reduce unnecessary Docker image layers

---

src/services/bitbucket/BitbucketService.spec.ts
src/services/bitbucket/BitbucketService.ts
src/test/factories/responses/bitbucket/listIssuesErrorResponseFactory.ts
src/test/helpers/bitbucketNock.ts

Handle error response from Bitbucket API in `BitbucketService.listIssues` if the project has issue tracker disabled. I have also added new error mock for bitbucketNock `listIssuesErrorResponse` to test the error condition.
Fixes #263

fix(bitbucket): Handle disabled issue tracker

---

src/practices/CSharp/C#GitignoreCorrectlySetPractice.spec.ts
src/practices/CSharp/C#GitignoreCorrectlySetPractice.ts
src/practices/Java/JavaGitignoreCorrectlySetPractice.spec.ts
src/practices/Java/JavaGitignoreCorrectlySetPractice.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.spec.ts
src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
src/practices/Ruby/RubyGitignoreCorrectlySetPractice.spec.ts
src/practices/Ruby/RubyGitignoreCorrectlySetPractice.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.spec.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts
src/practices/common/GitignoreCorrectlySetPracticeBase.ts

As discussed here https://github.com/DXHeroes/dx-scanner/pull/475#discussion_r515005847 I'm introducing a `GitignoreCorrectlySetPracticeBase` common base class for all gitignore correctly set practices to inherit from.
Open questions:
1. Java gitignore is the only one that throws an error in the `evaluate` method instead of returning `unknown` when no file inspector is present in the `PracticeContext`. Should this PR preserve the exception throwing or the `unknown` return value?
2. There is a race condition when more than one component is detected at the same path and a practice runs for each component. Since the practices run in parallel (or at least their IO does) there is a race condition as there is no locking mechanism. For example, when `RustComponentDetector` detects both …

feat: refactor practices into GitignoreCorrectlySetPracticeBase

---

action.yml

The argument type flag was missing. Therefore, secret token was considered an input path to scan
Related: #486

Add authorization arg specifier

---

src/detectors/Rust/RustComponentDetector.ts
src/detectors/Rust/RustLanguageDetector.ts
src/inspectors/package/RustPackageInspector.ts
src/practices/Rust/RustGitignoreCorrectlySetPractice.spec.ts
src/practices/Rust/RustGitignoreCorrectlySetPractice.ts

* More `async/await` in lieu of `Promise.all` and `.then` chains.
* Path joining using `path.join`
* Make use if `ErrorFactory.newInternalError` for unexpected state in component detector
* Rust gitignore practice hooked up to the GitignoreCorrectlySetPracticeBase from the other PR
Recently two of my PRs got merged, but one of them wasn't fully done. This PR cleans up the remaining issues

chore: clean up rust-related components

---

src/practices/JavaScript/ESLintWithoutErrorsPractice.ts
src/practices/JavaScript/ESlintWithoutErrorsPractice.spec.ts

Eslintrc.yml wasn't correctly loaded so eslint was using empty options argument and practice was falling. I also added `tsconfigRootDir` to make sure that eslint knows path to tsconfig when scanning typescript project.

fix: eslintrc yml not properly loaded

---

src/practices/Java/JavaGitignoreCorrectlySetPractice.ts
src/practices/TypeScript/TsGitignoreCorrectlySetPractice.ts
src/practices/common/GitignoreCorrectlySetPracticeBase.ts

We were looking for gitignore using wrong path. Method `checkFileInspector` in `GitignoreCorrectlySetPracticeBase` just returned `ctx.fileInspector` if there was a basePath in it. It didn't actually check if there is a gitignore file to read. Now we check if there is a gitignore otherwise we return `ctx.root.fileInspector` because we (thanks to gitignore is present practice) know there is a gitignore somewhere.

fix: gitignore is correctly set practice

---

src/collectors/ServiceDataCollector.ts
src/contexts/scanner/scannerContextBinding.ts
src/index.ts
src/reporters/DashboardReporter.spec.ts
src/reporters/DashboardReporter.ts

Make data collector optional.
Dxs didn't run if the user uses apiToken but uses unsupported VCS.

fix: make ServiceDataCollector optional

---

src/practices/JavaScript/JsLockfileIsPresentPractice.spec.ts
src/practices/JavaScript/JsLockfileIsPresentPractice.ts
src/practices/index.ts
src/scanner/IConfigProvider.ts

fix: make lockfile practice only for js and ts

---

README.md
src/test/factories/ArgumentsProviderFactory.ts

Change default value of `--fail` from `high` to `off`.
As discussed in #498 , we want to get rid of a situation when by default dx-scanner outputs exit code `1` if some high-impact practices fail.

feat: change default value of --fail flag

---

src/index.ts
src/practices/IPractice.ts
src/practices/JavaScript/ESLintWithoutErrorsPractice.ts
src/practices/PracticeUtils.ts
src/practices/utils/DependenciesVersionEvaluationUtils.ts
src/reporters/DashboardReporter.ts
src/reporters/DashboardReporterEnums.ts

Some refactoring of CLI startup to avoid unnecessary imports **without** breaking the interface of dx-scanner. The sub-command require is deferred and some other imports are split between the types and enums. With this change, types get compiled out in JS and enums are small to require.
Some PCs (my included) are made slower than others. And even for the fast ones, we want the CLI to start really fast. My aim here is to get the starting time (at least for "empty run") under 500ms. Time under 100ms would be really great.
Here are the mean times (10 runs) for current master and version in this MR (both with cold system cache and warm cache) for running the compiled version of dx-scanner:
| | Cold cache | Warm cache |
| --- | ---: | ---: |
| master | 3 249 ms | 1 831 ms |
| MR 551 | 702 ms | …

⚡  Better CLI startup time
